# Generated by Django 3.0.2 on 2020-01-25 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicesite', '0002_chlodzenie_dysk_kartagraficzna_monitor_obudowa_plytaglowna_procesor_ram_zestaw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='servicesite.Zestaw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
